micronaut:
  server:
    port: 8080   
akhq:
  connections:
    my-cluster:
      properties:
        bootstrap.servers: "virtualserver1:9092"
      connect:
        - name: connect_sink
          url: "http://virtualserver1:8083"
