global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["virtualserver1:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["virtualserver2:9100"]
