
export SPARK_MASTER_HOST=virtualserver2
export SPARK_WORKER_HOST=virtualserver2
export SPARK_MASTER_PORT=7077
export SPARK_WORKER_MEMORY=8g
export SPARK_WORKER_INSTANCES=1
export SPARK_WORKER_PORT=8888
export SPARK_LOCAL_IP=0.0.0.0
export SPARK_EXECUTOR_INSTANCES=4