- hosts: flink_cluster
  tasks:


  #   - name: Copy Flink job to the server
  #     # Kopírování Flink jobu na server
  #     copy:
  #       src: "flink-job.jar"
  #       dest: "/opt/flink-{{ flink_version }}/flink-job.jar"
  #     notify: Deploy Flink job

  # handlers:
  #   - name: Deploy Flink job
  #     # Nasazení Flink jobu
  #     shell: "/opt/flink-{{ flink_version }}/bin/flink run -d /opt/flink-{{ flink_version }}/flink-job.jar"
  #     async: 10
  #     poll: 0
  #     register: deploy_result
  #     until: deploy_result.rc == 0
  #     retries: 5
  #     delay: 10