- hosts: flink_cluster
  tasks:
    - name: Stop Task managers
      # Run Job Manager
      shell: "/opt/flink-{{ flink_version }}/bin/taskmanager.sh stop-all"
      async: 10
      poll: 0
    - name: Stop job managers
      # Stop Job Manager
      shell: "/opt/flink-{{ flink_version }}/bin/jobmanager.sh stop-all"
      async: 10
      poll: 0     
    - name: Stop cluster
      # Stop cluster
      shell: "/opt/flink-{{ flink_version }}/bin/stop-cluster.sh"
      async: 10
      poll: 0          